# Generated by Django 3.1.6 on 2024-07-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutreProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(default='', upload_to='fichiers/')),
                ('description', models.TextField(default='')),
                ('description_détaillé', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='catégorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='fichiers/')),
                ('desc_produit', models.TextField(default='')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popularité', models.CharField(max_length=100)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('créé_à', models.DateTimeField(auto_now_add=True)),
                ('catégories', models.ManyToManyField(to='Certifications.catégorie')),
                ('produits_similaires', models.ManyToManyField(to='Certifications.AutreProduit')),
            ],
        ),
        migrations.CreateModel(
            name='InformationComplémentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localiser_un_centre_de_test', models.TextField(blank=True, default='')),
                ('créer_un_compte', models.TextField(blank=True, default='')),
                ('attribuer_un_bon_à_votre_compte', models.TextField(blank=True, default='')),
                ('echanger_votre_bon_examen', models.TextField(blank=True, default='')),
                ('echanger_votre_test_pratique_via_GMetrix', models.TextField(blank=True, default='')),
                ('utiliser_le_bon', models.TextField(blank=True, default='')),
                ('domaines_objectifs', models.URLField(blank=True, default='', max_length=300)),
                ('fournisseur', models.CharField(blank=True, default='', max_length=200)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certifications.certification')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('créé_à', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certifications.certification')),
            ],
        ),
        migrations.AddField(
            model_name='autreproduit',
            name='catégories',
            field=models.ManyToManyField(to='Certifications.catégorie'),
        ),
    ]
