# Generated by Django 3.1.6 on 2024-07-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autreproduit',
            name='description_détaillé',
        ),
    ]
