# Generated by Django 3.1.6 on 2024-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certifications', '0002_remove_autreproduit_description_détaillé'),
    ]

    operations = [
        migrations.AddField(
            model_name='autreproduit',
            name='desc_detaille',
            field=models.TextField(default=''),
        ),
    ]
