# Generated by Django 3.1.7 on 2024-07-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Certifications', '0003_autreproduit_desc_detaille'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='produit_similaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Certifications.autreproduit'),
        ),
    ]
