# Generated by Django 3.1.7 on 2024-07-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certifications', '0005_auto_20240721_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='note_moyenne',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
