# Generated by Django 3.1.7 on 2024-07-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certifications', '0007_autreproduit_note_moyenne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certif_mieux_notee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.ManyToManyField(to='Certifications.Certification')),
            ],
        ),
    ]
