# Generated by Django 3.1.6 on 2024-07-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fichiers/')),
                ('date', models.DateField(blank=True, null=True)),
                ('categorie', models.ManyToManyField(to='Formations.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='FormationAVenir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('heure_debut', models.TimeField(default='00:00:00')),
                ('heure_fin', models.TimeField(default='00:00:00')),
                ('image', models.ImageField(upload_to='fichiers/')),
                ('description', models.TextField(default='')),
                ('prix', models.DecimalField(decimal_places=4, max_digits=10)),
                ('inscri_deadline', models.DateField(blank=True, null=True)),
                ('heure_deadline', models.TimeField(default='00:00:00')),
                ('organisateurs', models.CharField(default='', max_length=200)),
                ('adresse_mail_organisateurs', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('categorie', models.ManyToManyField(to='Formations.Categories')),
            ],
        ),
    ]
