# Generated by Django 3.1.6 on 2024-07-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationavenir',
            name='adresse_mail_organisateurs',
        ),
    ]
