# Generated by Django 3.1.6 on 2024-07-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0003_formationavenir_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
