# Generated by Django 3.1.6 on 2024-07-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0004_formationavenir_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='google_agenda',
            field=models.URLField(blank=True),
        ),
    ]
