# Generated by Django 3.1.6 on 2024-07-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0005_formationavenir_google_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='yahoo',
            field=models.URLField(blank=True),
        ),
    ]
