# Generated by Django 3.1.6 on 2024-07-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0006_formationavenir_yahoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='outlook',
            field=models.URLField(blank=True),
        ),
    ]
