# Generated by Django 3.1.6 on 2024-07-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0007_formationavenir_outlook'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='objectifs',
            field=models.TextField(default=''),
        ),
    ]
