# Generated by Django 3.1.6 on 2024-07-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0008_formationavenir_objectifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='public_visé',
            field=models.TextField(default=''),
        ),
    ]
