# Generated by Django 3.1.6 on 2024-07-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0010_formationavenir_positionnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='methode',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='formationavenir',
            name='organisation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='formationavenir',
            name='sanction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='formationavenir',
            name='validation',
            field=models.TextField(default=''),
        ),
    ]
