# Generated by Django 3.1.6 on 2024-07-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0011_auto_20240711_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='prérequis',
            field=models.TextField(default=''),
        ),
    ]
