# Generated by Django 3.1.6 on 2024-07-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0012_formationavenir_prérequis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('titre_jour', models.CharField(max_length=200)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.formationavenir')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('description', models.TextField()),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formations.programmeformation')),
            ],
        ),
    ]
