# Generated by Django 3.1.6 on 2024-07-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0013_module_programmeformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='nom_formateur',
            field=models.CharField(default='', max_length=200),
        ),
    ]
