# Generated by Django 3.1.6 on 2024-07-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0015_formationavenir_image_formateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='titre_formateur',
            field=models.CharField(default='', max_length=200),
        ),
    ]
