# Generated by Django 3.1.6 on 2024-07-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0016_formationavenir_titre_formateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='fichiers/')),
            ],
        ),
        migrations.RemoveField(
            model_name='formationavenir',
            name='image_formateur',
        ),
        migrations.RemoveField(
            model_name='formationavenir',
            name='nom_formateur',
        ),
        migrations.RemoveField(
            model_name='formationavenir',
            name='titre_formateur',
        ),
        migrations.AddField(
            model_name='formationavenir',
            name='formateurs',
            field=models.ManyToManyField(to='Formations.Formateur'),
        ),
    ]
