# Generated by Django 3.1.6 on 2024-07-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0017_auto_20240712_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
