# Generated by Django 3.1.6 on 2024-07-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0018_formateur_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='article',
            field=models.URLField(blank=True),
        ),
    ]
