# Generated by Django 3.1.6 on 2024-07-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0019_formateur_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='dates_et_lieu_description',
            field=models.TextField(default=''),
        ),
    ]
