# Generated by Django 3.1.6 on 2024-07-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0021_avis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avis',
        ),
    ]
