# Generated by Django 3.1.6 on 2024-07-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0023_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='informations_pratiques',
            field=models.TextField(default=''),
        ),
    ]
