# Generated by Django 3.1.6 on 2024-07-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0024_formationavenir_informations_pratiques'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationavenir',
            name='formations_connexes',
            field=models.ManyToManyField(to='Formations.Formations'),
        ),
    ]
