# Generated by Django 3.1.6 on 2024-07-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0026_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='BilletAchat',
        ),
        migrations.RenameField(
            model_name='billetachat',
            old_name='created_at',
            new_name='date_achat',
        ),
        migrations.RenameField(
            model_name='billetachat',
            old_name='quantity',
            new_name='quantité',
        ),
    ]
