# Generated by Django 3.1.6 on 2024-07-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0027_auto_20240714_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='billetachat',
            name='titre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
