# Generated by Django 3.1.6 on 2024-07-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0028_billetachat_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='note',
            field=models.IntegerField(default=0),
        ),
    ]
