# Generated by Django 3.1.6 on 2024-07-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0029_avis_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='comment',
            new_name='commentaire',
        ),
    ]
