# Generated by Django 3.1.7 on 2024-07-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0030_auto_20240719_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationavenir',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
