# Generated by Django 3.1.7 on 2024-07-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0031_auto_20240723_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationavenir',
            name='formations_connexes',
            field=models.ManyToManyField(blank=True, related_name='_formationavenir_formations_connexes_+', to='Formations.FormationAVenir'),
        ),
        migrations.DeleteModel(
            name='Formations',
        ),
    ]
