# Generated by Django 3.1.7 on 2024-07-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0032_auto_20240726_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationavenir',
            name='formations_connexes',
        ),
        migrations.AddField(
            model_name='formationavenir',
            name='Formations_formationavenir_formations_connexes',
            field=models.ManyToManyField(blank=True, related_name='_formationavenir_Formations_formationavenir_formations_connexes_+', to='Formations.FormationAVenir'),
        ),
    ]
