# Generated by Django 3.1.7 on 2024-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formations', '0035_dateformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateformation',
            name='heure_debut',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='dateformation',
            name='heure_fin',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
